Attempt to fix an obscure Zenmap crash:
Traceback (most recent call last):
  File "zenmapGUI\ScanScanListPage.pyo", line 100, in _row_changed
  File "zenmapGUI\ScanScanListPage.pyo", line 108, in _update
AttributeError: 'NoneType' object has no attribute 'get_selected_rows'

Despite my best efforts, I can't reproduce it or even figure out what might
cause it to happen. But it is pretty common: 279 crash reports since
2008-10-07.