Repair a crash from an automatic crash report, apparently due to some cut-and-paste code. The crash was
Traceback (most recent call last):
  File "zenmapGUI\ScanNotebook.pyo", line 314, in _remove_scan_cb
  File "zenmapGUI\ScanNotebook.pyo", line 515, in update_ui
  File "zenmapGUI\TopologyPage.pyo", line 92, in update_radialnet
  File "radialnet\util\integration.pyo", line 453, in make_graph_from_hosts
  File "radialnet\util\integration.pyo", line 134, in set_node_info
UnboundLocalError: local variable 'osclass' referenced before assignment