Merged -r13793:HEAD from nmap-exp/dev/nmap/zenmap branch now that we're opening up trunk development again.  Here are the items which were merged:
------------------------------------------------------------------------
r13966 | david | 2009-06-29 13:05:09 -0700 (Mon, 29 Jun 2009) | 26 lines

Refactor the code that counts ports in a HostInfo and fix some bugs.
First, the code would fail unnecessarily if a port didn't have a state:

Traceback (most recent call last):
  File "zenmapGUI\ScanNotebook.pyo", line 411, in verify_execution
  File "zenmapGUI\ScanNotebook.pyo", line 458, in load_from_command
  File "zenmapGUI\ScanNotebook.pyo", line 515, in update_ui
  File "zenmapGUI\TopologyPage.pyo", line 92, in update_radialnet
  File "radialnet\util\integration.pyo", line 453, in make_graph_from_hosts
  File "radialnet\util\integration.pyo", line 59, in set_node_info
  File "radialnet\util\integration.pyo", line 39, in calc_vulnerability_level
  File "zenmapCore\NmapParser.pyo", line 263, in get_open_ports
KeyError: 'port_state'

I didn't think Nmap can produce such output but it appeared in a Zenmap
crash report.

Second, the code determined whether a port was open, for example, by
searching the state string for "open". That was fine for "open" and
"closed" but would cause "unfiltered" to be counted as "filtered". Now
the applicable states are explicitly listed:

open: open, open|filtered
closed: closed, closed|filtered
filtered: filtered, open|filtered, closed|filtered

------------------------------------------------------------------------
r13814 | josh | 2009-06-17 21:34:15 -0700 (Wed, 17 Jun 2009) | 3 lines

[zenmap] Added support to zenmap for the new SCTP options: -PY, -sY and -sZ