Don't try to restore an unset sort column.
I don't know how the sort column is getting unset, but people are
getting Zenmap crashes when get_sort_column_id is returning (None, None)
and that tuple is fed back into set_sort_column_id:

Traceback (most recent call last):
  File "zenmapGUI\ScanInterface.pyo", line 536, in verify_execution
  File "zenmapGUI\ScanInterface.pyo", line 582, in load_from_command
  File "zenmapGUI\ScanInterface.pyo", line 629, in update_ui
  File "zenmapGUI\ScanHostsView.pyo", line 277, in mass_update
TypeError: an integer is required