Here's a fix for another bug I can't reproduce:
  File "/usr/local/lib/python2.5/site-packages/zenmapGUI/NmapOutputViewer.py", l
ine 349, in refresh_output
    at_end = (v_adj.value >= v_adj.upper - v_adj.page_size)
AttributeError: 'NoneType' object has no attribute 'value'

I suspect it is caused by a bug in an old version of PyGTK.