Fix compiler errors: .\ncat_broker.c(292) : error C2440: '=' : cannot convert from 'void *' to 'char *'         Conversion from 'void*' to pointer to non-'void' requires an explicit cast .\ncat_broker.c(305) : error C2440: '=' : cannot convert from 'void *' to 'char *'         Conversion from 'void*' to pointer to non-'void' requires an explicit cast