Initialize a state variable, in_hostnames, in NmapParser.py. Not having it caused a crash when an XML file didn't have a hostnames element. It looked like   File "zenmapGUI\ScanNotebook.pyo", line 387, in verify_execution   File "zenmapGUI\ScanNotebook.pyo", line 400, in load_from_command   File "zenmapGUI\ScanNotebook.pyo", line 444, in _parse   File "zenmapCore\NmapParser.pyo", line 749, in parse_file   File "zenmapCore\NmapParser.pyo", line 743, in parse   File "xml\sax\expatreader.pyo", line 107, in parse   File "xml\sax\xmlreader.pyo", line 123, in parse   File "xml\sax\expatreader.pyo", line 207, in feed   File "xml\sax\expatreader.pyo", line 301, in start_element   File "zenmapCore\NmapParser.pyo", line 920, in startElement AttributeError: 'NmapParserSAX' object has no attribute 'in_hostnames'