Add a missing format specifier in a string in the German translation, to avoid this crash when opening the About window:
Traceback (most recent call last):
  File "zenmapGUI\MainWindow.pyo", line 631, in _show_about_cb
  File "zenmapGUI\About.pyo", line 178, in __init__
TypeError: not all arguments converted during string formatting