Remove the PYTHONPATH and PYTHONHOME variables from the environment before executing a sub-ndiff. These variables are set by py2app to point inside our application bundle. Having them set in the environment makes Ndiff use the same settings because it is also a Python application. It causes this error because the bundled i386/ppc library doesn't match the system's x64_64 Python interpreter.
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/usr/local/bin/ndiff", line 16, in <module>
    import datetime
ImportError: /Users/david/nmap/zenmap/dist/Zenmap.app/Contents/Resources/lib/python2.6/lib-dynload/datetime.so: no appropriate 64-bit architecture (see "man python" for running in 32-bit mode)

Deleting the variables is somewhat wrong, because the user may have set those
outside of Zenmap expecting them to be used with their system-installed Python
programs. But this is at least no worse than before, because previously py2app
was stomping on the variables anyway.