Use time.ctime rather than time.strftime("%B %d, %Y - %H:%M") to format the startstr attribute of the nmaprun element in XML output. This is because Nmap uses ctime, and because strftime is affected by locale. The locale dependence could lead to a crash on systems using the old PyXML library, which for some reason does a UTF-8 decoding step on the arguments it gets passed for attributes. For example, running Zenmap in an Arabic locale:
LANG=ar_IQ zenmap

would crash when saving a file:

  File "/usr/lib/python2.6/site-packages/zenmapCore/NetworkInventory.py", line 220, in save_to_file
    self.get_scans()[index].write_xml(f)
  File "/usr/lib/python2.6/site-packages/zenmapCore/NmapParser.py", line 955, in write_xml
    self._write_nmaprun(writer)
  File "/usr/lib/python2.6/site-packages/zenmapCore/NmapParser.py", line 1239, in _write_nmaprun
    xmloutputversion = str(XML_OUTPUT_VERSION))))
  File "/usr/lib/python2.6/site-packages/_xmlplus/sax/saxutils.py", line 255, in startElement
    writeattr(self._out, value)
  File "/usr/lib/python2.6/site-packages/_xmlplus/sax/saxutils.py", line 216, in writeattr
    writetext(stream, text, entities)
  File "/usr/lib/python2.6/site-packages/_xmlplus/sax/saxutils.py", line 188, in writetext
    stream.write(escape(text, entities))
  File "/usr/lib/python2.6/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 0-1: invalid data

The reason for this is that time.strftime would return a byte string
like "Ø£ÙØªÙØ¨Ø± 15, 2009 - 08:56", however encoded in ISO-8859-6 not UTF-8.