Remove -oN and -oX options more intelligently in NmapParser. Previously it would crash when loading a file with
<nmaprun args="nmap -oX -oX localhost"/>

That's because the parser would notice there were two -oX, and for each one
would try to delete it and the following argument. Of course both -oX were
deleted the first time, and the second time failed with

ValueError: list.index(x): x not in list