Include "gio" among the packages included for py2exe. Since upgrading my GTK+ to 2.18.7, I had been getting this error in zenmap.exe.log:
RuntimeWarning: tp_compare didn't return -1 or -2 for exception
RuntimeWarning: tp_compare didn't return -1 or -2 for exception
Traceback (most recent call last):
  File "zenmap", line 91, in <module>
  File "zenmapGUI\App.pyo", line 116, in <module>
  File "zenmapGUI\higwidgets\__init__.pyo", line 100, in <module>
  File "zenmapGUI\higwidgets\higboxes.pyo", line 99, in <module>
AttributeError: 'module' object has no attribute 'Box'

Zenmap didn't start up. I finally found a clue at
http://sourceforge.net/mailarchive/message.php?msg_name=4BB5AC30.1030408%40gmail.com.