In ncat_main.cc, move sockaddr_in sin and sockaddr_in6 sin6 to function-level scope rather than file-level scope, because Visual C++ complains: 	error C2365: 'sin' : redefinition; previous definition was 'function'