Encode the database file name to UTF-8. This is because of a bug in pysqlite 2.4.0. It was fixed in 2.4.1: http://oss.itsystementwicklung.de/trac/pysqlite/wiki/2.4.1_Changelog. Using 2.4.0 before caused a crash like
Traceback (most recent call last):
  File "/usr/local/bin/zenmap", line 98, in <module>
    import zenmapGUI.App
  File "/usr/local/lib/python2.5/site-packages/zenmapGUI/App.py", line 47, in <module>
    from zenmapCore.UmitDB import UmitDB
  File "/usr/local/lib/python2.5/site-packages/zenmapCore/UmitDB.py", line 64, in <module>
    connection = sqlite.connect(umitdb)
ValueError: database parameter must be string or APSW Connection object